#################################################################################################
#
#    ██╗████████╗███████╗███╗   ███╗██╗   ██╗ ██████╗ ██████╗ ███╗   ██╗███████╗██╗ ██████╗
#    ██║╚══██╔══╝██╔════╝████╗ ████║╚██╗ ██╔╝██╔════╝██╔═══██╗████╗  ██║██╔════╝██║██╔════╝
#    ██║   ██║   ███████╗██╔████╔██║ ╚████╔╝ ██║     ██║   ██║██╔██╗ ██║█████╗  ██║██║  ███╗
#    ██║   ██║   ╚════██║██║╚██╔╝██║  ╚██╔╝  ██║     ██║   ██║██║╚██╗██║██╔══╝  ██║██║   ██║
#    ██║   ██║   ███████║██║ ╚═╝ ██║   ██║   ╚██████╗╚██████╔╝██║ ╚████║██║     ██║╚██████╔╝
#    ╚═╝   ╚═╝   ╚══════╝╚═╝     ╚═╝   ╚═╝    ╚═════╝ ╚═════╝ ╚═╝  ╚═══╝╚═╝     ╚═╝ ╚═════╝
#
#      Contact: Théo#0001
#      Support: https://itsme.to/discord
#      Documentation: https://itsme.to/itsmyconfig
#
#################################################################################################

symbol-prefix: "$"

custom-placeholder:
  example:
    value: "Example placeholder"
    requirements:
      example:
        type: "=="
        input: 100
        output: 200
        deny: "&cYou don't have enough money !"

custom-progress:
  basic:
    symbol: "⦁●⚫●⚫●⚫●⚫●⚫●⚫●⚫●⚫●⚫●⚫●⦁"
    completed-color: "&a"
    progress-color: "&e"
    remaining-color: "&7"

messages:
  invalidUse:
    - "&c&lERROR &f┃ Invalid use"
    - "  &e/{usage}"
  reload:
    - "&a&lSUCCES &f┃ ItsmyConfig &freloaded !"
  nopermission:
    - "&a&lERROR &f┃ You don't have permission"
  messageSend:
    - "&a&lSUCCES &f┃ Message Send !"
  commandAdded:
    - "&a&lSUCCESS &f┃ The command has been added to &b{player}"
