#################################################################################################
#
#    ██╗████████╗███████╗███╗   ███╗██╗   ██╗ ██████╗ ██████╗ ███╗   ██╗███████╗██╗ ██████╗
#    ██║╚══██╔══╝██╔════╝████╗ ████║╚██╗ ██╔╝██╔════╝██╔═══██╗████╗  ██║██╔════╝██║██╔════╝
#    ██║   ██║   ███████╗██╔████╔██║ ╚████╔╝ ██║     ██║   ██║██╔██╗ ██║█████╗  ██║██║  ███╗
#    ██║   ██║   ╚════██║██║╚██╔╝██║  ╚██╔╝  ██║     ██║   ██║██║╚██╗██║██╔══╝  ██║██║   ██║
#    ██║   ██║   ███████║██║ ╚═╝ ██║   ██║   ╚██████╗╚██████╔╝██║ ╚████║██║     ██║╚██████╔╝
#    ╚═╝   ╚═╝   ╚══════╝╚═╝     ╚═╝   ╚═╝    ╚═════╝ ╚═════╝ ╚═╝  ╚═══╝╚═╝     ╚═╝ ╚═════╝
#
#      Contact: Théo#0001
#      Support: https://itsme.to/discord
#      Documentation: https://itsme.to/itsmyconfig
#
#################################################################################################

symbol-prefix: "$"
custom-placeholder:
  prefix:
    value: "<gradient:#ff0f7b:#f89b29><bold>ServerName</bold></gradient> <white>┃"
  #Do not modify {0}, it's a variable to get the content.
  #You also need to keep the tag closed.
  color:
    value: "<yellow>{0}</yellow>"
  error:
    value: "<red><bold>ERROR</bold></red> <white>┃"

  example:
    value: "Example placeholder"
    requirements:
      example:
        type: "=="
        input: 100
        output: 200
        deny: "&cYou don't have enough money !"

custom-progress:
  basic:
    symbol: "⦁●⚫●⚫●⚫●⚫●⚫●⚫●⚫●⚫●⚫●⚫●⦁"
    completed-color: "&a"
    progress-color: "&e"
    remaining-color: "&7"

messages:
  invalid-use:
    - "<red><bold>ERROR</bold></red> <white>┃ Invalid use"
    - "  <yellow>/<usage>"
  reload:
    - "<green><bold>SUCCES</bold></green> <white>┃ ItsmyConfig &freloaded !"
  no-permission:
    - "<red><bold>ERROR</bold></red> <white>┃ You don't have permission"
  message-sent:
    - "<green><bold>SUCCES</bold></green> <white>┃ Message Sent !"
