name: ItsMyConfig
version: ${version}
authors: [iiAhmedYT, RealAlphaUA]
main: to.itsme.itsmyconfig.ItsMyConfig
api-version: 1.13
depend:
  - ProtocolLib
  - PlaceholderAPI
commands:
  message:
    permission: "itsmyconfig.message"
  itsmyconfig:
    permission: "itsmyconfig.reload"