name: ItsMyConfig
version: ${project.version}
author: RealAlphaUA
main: ua.realalpha.itsmyconfig.ItsMyConfig
api-version: 1.13
depend:
  - ProtocolLib
  - PlaceholderAPI

commands:
  message:
    permission: "itsmyconfig.message"
  itsmyconfig:
    permission: "itsmyconfig.reload"